main: me.ItemBank.main.ItemBank
name: ItemBank
author: CJM
version: 0.2
api-version: 1.15
description: Item bank
commands:
   createbank:
      usage: /CreateBank
      description: Creates a bank when looking at a sign
      aliases: [cb]
   help:
      usage: /Help
      description: Shows a list of commands