main: me.ItemBank.main.ItemBank
name: ItemBank
author: CJM
version: 1.9.0
api-version: 1.21
description: Item bank
commands:
   createbank:
      usage: /CreateBank
      description: Creates a bank when looking at a sign
      aliases:
      - cb
   openbank:
      usage: /openbank
      description: Opens bank for player
      aliases:
      - ob
   reloadconfig:
      usage: /reloadconfig
      description: reloads config file
      aliases: rc
   help:
      usage: /Help
      description: Shows a list of commands
permissions:
   ItemBank.Createbank:
      parent node: ItemBank
      default: false
   ItemBank.OpenBank:
      parent node: ItemBank
      default: false
   ItemBank.Help:
      parent node: ItemBank
      default: true